### ISSUE TITLE
সংশোধন প্রয়োজন : পেঙ্গুইনস ক্লাব -> "দি" পেঙ্গুইনস ক্লাব

### ISSUE THREAD

**Issue by imahbub** [fazlerabbi37/bd-startups#13]
পেঙ্গুইনস ক্লাব এর পরিবর্তে "দি পেঙ্গুইনস ক্লাব" সংশোধন করা হোক এবং বিবরণ পরিবর্তন করা হোক। 

নাম : **"দি পেঙ্গুইনস ক্লাব"**
বিবরণ : **"ওপেন সোর্স, লিনাক্স, ব্যবসা, প্রাইভেসি এবং নিরাপত্তা বিষয়ক দৈনিক বাংলা ম্যাগাজিন"**

রেফারেন্স : [The Penguins Club](https://thepenguins.club)

**Comment by fazlerabbi37** [comment]
fixed with adac3d2
