### ISSUE TITLE
বানান নিশ্চিতকরন : ইনক্লাশন এক্স -> ইনক্লুশন এক্স

### ISSUE THREAD

**Issue by imahbub** [fazlerabbi37/bd-startups#19]
ইনক্লাশন এক্স : মানসিক স্বাস্থ্য সেবা এন্ট্রিটির সঠিক বানান নিশ্চিত করার অনুরোধ করছি, এটি আমার মতে "ইনক্লুশন এক্স" হবে। ছবিতে উচ্চারনরীতি এবং ডিকশনারি এন্ট্রি।

![image](https://user-images.githubusercontent.com/63340482/146380986-c74b77c8-b090-48a1-b5ef-14bdf8414714.png)

আরো রেফারেন্স

[How to pronounce Inclusion - YouTube](https://www.youtube.com/watch?v=TnUZ8HP0jE8)

**Comment by fazlerabbi37** [comment]
fixed with f801b2
